**❓ What is Pandas**

Pandas is a Python library used for loading, cleaning, and analyzing data. It provides easy to use tools like Series and DataFrames for working with structured datasets.

**⚙️ Why Pandas is Important in Machine Learning**

Pandas is the **go-to library for data manipulation and analysis** in Machine Learning.  
It is built on top of NumPy and provides easy-to-use data structures like **Series** and **DataFrame**.

**🔍 Why Pandas is Essential:**
- 📂 **Data Handling:** Load, clean, and preprocess real-world datasets (CSV, Excel, SQL, JSON).
- 🧭 **Data Exploration:** Understand your data — structure, missing values, correlations.
- ⚙️ **Integration with ML:** Works seamlessly with Scikit-Learn, NumPy, Matplotlib, and Seaborn.
- 📈 **Feature Engineering:** Create, transform, and select useful features for models.
- 🔢 **Efficient Operations:** Built on NumPy, so it’s fast and memory-efficient.

> 💡 *Pandas turns messy, raw data into clean, model-ready data.*

---

**Install and Import Pandas library**

In [1]:
%pip install -U -q pandas

Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

**Series (1D data)**

In [3]:
s = pd.Series([10, 20, 30, 40, 50], name="Marks")

In [4]:
print(type(s))

<class 'pandas.Series'>

In [5]:
print(s)

0    10
1    20
2    30
3    40
4    50
Name: Marks, dtype: int64

In [6]:
print(s[0])
print(s.mean())

10
30.0

**DataFrame (2D data)**

In [7]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "Michelle"],
    "Age": [24, 32, 27, 23],
    "Score": [85, 91, 78, 88],
}

data_frame = pd.DataFrame(data)

In [8]:
print(type(data_frame))

<class 'pandas.DataFrame'>

In [9]:
print(data_frame)

       Name  Age  Score
0     Alice   24     85
1       Bob   32     91
2   Charlie   27     78
3  Michelle   23     88

In [10]:
data_frame.head() # data_frame.tail()

       Name  Age  Score
0     Alice   24     85
1       Bob   32     91
2   Charlie   27     78
3  Michelle   23     88

In [11]:
# saving the dataframe to a csv file
data_frame.to_csv("sample_data.csv", index=False)

**Read data from a csv file**

In [12]:
diabetes_df = pd.read_csv("diabetes.csv")

In [13]:
diabetes_df.shape

(768, 9)

In [14]:
diabetes_df.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='str')

In [15]:
diabetes_df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [16]:
diabetes_df.tail()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [17]:
# read sample_data.csv and analyse it
df = pd.read_csv("sample_data.csv")

In [18]:
df.shape

(4, 3)

In [19]:
df

       Name  Age  Score
0     Alice   24     85
1       Bob   32     91
2   Charlie   27     78
3  Michelle   23     88

In [20]:
df.head() # first 5 rows in the dataframe

       Name  Age  Score
0     Alice   24     85
1       Bob   32     91
2   Charlie   27     78
3  Michelle   23     88

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

**Inspecting the data**

In [22]:
print("Shape:", df.shape)
print("\nColumns:", df.columns)
print("\nData Types:\n", df.dtypes)

Shape: (4, 3)

Columns: Index(['Name', 'Age', 'Score'], dtype='str')

Data Types:
 Name       str
Age      int64
Score    int64
dtype: object

**Selecting the data**

In [23]:
# single column
print(df["Name"]) # series

0       Alice
1         Bob
2     Charlie
3    Michelle
Name: Name, dtype: str

In [24]:
# multiple columns
print(df[["Name", "Age"]])

       Name  Age
0     Alice   24
1       Bob   32
2   Charlie   27
3  Michelle   23

In [25]:
# row selection
print(df.iloc[1]) # by position of row

Name     Bob
Age       32
Score     91
Name: 1, dtype: object

In [26]:
print(df.loc[1]) # by label/index

Name     Bob
Age       32
Score     91
Name: 1, dtype: object

In [27]:
data_frame_2 = pd.DataFrame(data, index=["a", "b", "c", "d"])

In [28]:
data_frame_2.head()

       Name  Age  Score
a     Alice   24     85
b       Bob   32     91
c   Charlie   27     78
d  Michelle   23     88

In [29]:
data_frame_2.iloc[2]

Name     Charlie
Age           27
Score         78
Name: c, dtype: object

In [30]:
data_frame_2.loc["c"]

Name     Charlie
Age           27
Score         78
Name: c, dtype: object

**Filtering data**

In [31]:
df

       Name  Age  Score
0     Alice   24     85
1       Bob   32     91
2   Charlie   27     78
3  Michelle   23     88

In [32]:
high_scores = df[df["Score"] > 85]
high_scores

       Name  Age  Score
1       Bob   32     91
3  Michelle   23     88

In [33]:
low_scores = df[df["Score"] <= 85]
low_scores

      Name  Age  Score
0    Alice   24     85
2  Charlie   27     78

**Adding new column**

In [34]:
df["Passed"] = df["Score"] > 80
df

       Name  Age  Score  Passed
0     Alice   24     85    True
1       Bob   32     91    True
2   Charlie   27     78   False
3  Michelle   23     88    True

In [35]:
df["Age_To_Score_Ratio"] = df["Age"] / df["Score"]
df

       Name  Age  Score  Passed  Age_To_Score_Ratio
0     Alice   24     85    True            0.282353
1       Bob   32     91    True            0.351648
2   Charlie   27     78   False            0.346154
3  Michelle   23     88    True            0.261364

In [36]:
df["City"] = ["Warsaw", "Lublin", "Katowice", "Poznan"]
df

       Name  Age  Score  Passed  Age_To_Score_Ratio      City
0     Alice   24     85    True            0.282353    Warsaw
1       Bob   32     91    True            0.351648    Lublin
2   Charlie   27     78   False            0.346154  Katowice
3  Michelle   23     88    True            0.261364    Poznan

**Descriptive Statistics**

In [37]:
print("Max score:", df["Score"].max())
print("Min score:", df["Score"].min())
print("Average score:", df["Score"].mean())

Max score: 91
Min score: 78
Average score: 85.5

In [38]:
df.describe()

             Age      Score  Age_To_Score_Ratio
count   4.000000   4.000000            4.000000
mean   26.500000  85.500000            0.310380
std     4.041452   5.567764            0.045354
min    23.000000  78.000000            0.261364
25%    23.750000  83.250000            0.277106
50%    25.500000  86.500000            0.314253
75%    28.250000  88.750000            0.347527
max    32.000000  91.000000            0.351648

**Handling missing data**

In [39]:
df2 = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", None],
    "Age": [24, None, 27, 23],
    "Score": [85, 91, None, 88],
})

In [40]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob   NaN   91.0
2  Charlie  27.0    NaN
3      NaN  23.0   88.0

In [41]:
df2.dropna(subset=["Name"], inplace=True)

In [42]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob   NaN   91.0
2  Charlie  27.0    NaN

In [43]:
df2["Age"] = df2["Age"].fillna(df2["Age"].mean())
df2["Score"] = df2["Score"].fillna(df2["Score"].mean())

In [44]:
df2.head()

      Name   Age  Score
0    Alice  24.0   85.0
1      Bob  25.5   91.0
2  Charlie  27.0   88.0